#!/usr/bin/env python
import sys
from gwpy.table.lsctables import SnglBurstTable
from matplotlib import pyplot
print sys.argv[1]
events = SnglBurstTable.read(sys.argv[1])
#del events[10000:]
plot = events.plot('time', 'central_freq', "duration", "bandwidth", color='snr')
#plot = events.plot('time', 'central_freq', color='snr')
#plot.set_yscale("log")
plot.set_ylim(1e-0, 250)
t0 = 1153742417
plot.set_xlim(t0 + 0*60, t0 + 1*60)
#plot.set_xlim(t0 + 28, t0 + 32)
pyplot.axvline(t0 + 30, color='r')
cb = plot.add_colorbar(cmap='viridis')
plot.savefig("triggers.png")
